PRODUCT_VERSION_MAJOR = 13
PRODUCT_VERSION_MINOR = 0

ITTECH_VERSION := 0.1-eta
ITTECH_VARIANT := OS

# Internal version
LINEAGE_VERSION := ittech$(ITTECH_VARIANT)-$(PRODUCT_VERSION_MAJOR).$(PRODUCT_VERSION_MINOR)-$(shell date +%Y%m%d)-$(LINEAGE_BUILD)-v$(ITTECH_VERSION)

# Display version
LINEAGE_DISPLAY_VERSION := ittech$(ITTECH_VARIANT)-$(PRODUCT_VERSION_MAJOR).$(PRODUCT_VERSION_MINOR)-$(LINEAGE_BUILD)-v$(ITTECH_VERSION)
